---
name: ci

"on":
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get -y install build-essential autoconf dump kpartx fdisk qemu-utils
      - name: Build
        run: |
          ./autogen.sh
          ./configure
          make
          sudo make install
